export const FILESYSTEM_STRATEGY = {
  local: "LOCAL_STORAGE_SERVICE",
  aws: "AWS_STORAGE_SERVICE",
  google: "GOOGLE_STORAGE_SERVICE",
  digitalOcean: "DIGITALOCEAN_STORAGE_SERVICE",
  cloudinary: "CLOUDINARY_STORAGE_SERVICE"
}
